# Generated by Django 5.2.3 on 2026-07-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_staffprofile_order_assigned_staff_order_claimed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Preparing', 'Preparing'), ('Ready for pickup', 'Ready for pickup'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Processing', max_length=20),
        ),
    ]
