# Generated by Django 6.0 on 2026-01-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('Hot Coffee', 'Hot Coffee'), ('Cold Coffee', 'Cold Coffee'), ('Tea', 'Tea'), ('Snacks', 'Snacks')], default='Hot Coffee', max_length=50)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('rating', models.FloatField(default=4.5)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
