# Generated by Django 5.2.3 on 2026-07-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Hot Coffee', 'Hot Coffee'), ('Cold Coffee', 'Cold Coffee'), ('Tea', 'Tea'), ('Bakery', 'Bakery'), ('Breakfast', 'Breakfast'), ('Snacks', 'Snacks')], default='Hot Coffee', max_length=50),
        ),
    ]
